// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace GauravCrudNagpur.Models
{
    public partial class GauravTestContext : DbContext
    {
        public GauravTestContext()
        {
        }

        public GauravTestContext(DbContextOptions<GauravTestContext> options)
            : base(options)
        {
        }

     
    }
}