// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GauravCrudNagpur.Models
{
    [Table("information")]
    public partial class Information
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Fullname { get; set; }
        [Column("gender")]
        [StringLength(10)]
        [Unicode(false)]
        public string Gender { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateOfBirth { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Nationality { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Country { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string State { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Photo { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Details { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Address { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Hobby { get; set; }
    }
}